const NAMESPACE = 'ACTION';

export const SAVE_NAME = `${NAMESPACE}/SAVE_NAME`;
export const SAVE_TOP_COLOR = `${NAMESPACE}/SAVE_TOP_COLOR`;
export const SAVE_SETTING_COLOR = `${NAMESPACE}/SAVE_SETTING_COLOR`;
